### ISSUE TITLE
Redundant appearance of `company-complete` when aborting `helm-company`

### ISSUE THREAD

**Issue by ghost** [Sodel-the-Vociferous/helm-company#7]
Hi again,

I test your newest helm-company (0.1.2), and see that the `company-complete` window unexpectedly appears after aborting the `helm-company`.

Steps to reproduce:

- Call `M-x helm-company` => the `helm-company` window appear. 
- Press `C-g`, then the `helm-company` window disappear but the `company-complete` window appears.

Could you please check this issue?

Thanks!

**Comment by Sodel-the-Vociferous** [comment]
Whoops! I thought I fixed this (issue #5). I'll look into this.

**Comment by Sodel-the-Vociferous** [comment]
I can't duplicate this on `master`. I know the MELPA version still has this glitch. Are you sure you're running the latest one, and that you don't have a stale `helm-company.elc` bytecode file? (Try deleting the bytecode file -- it should get recompiled.)

**Comment by ghost** [comment]
Yes, I updated the newest code, revision https://github.com/Sodel-the-Vociferous/helm-company/commit/29ac90c4cb4c47563ba602af5438973cdc6a716c.

I tried it on another machine and the bug still occurs.

**Comment by ghost** [comment]
Hi, I tried the newest version https://github.com/Sodel-the-Vociferous/helm-company/commit/41beb48a5e753d115026f0dc273c29ffccae7d9f but the bug still occurs.

**Comment by Sodel-the-Vociferous** [comment]
I still can't reproduce it. When I get a little more time, I'll download your emacs configuration and try testing with that.

**Comment by Sodel-the-Vociferous** [comment]
I still cannot reproduce this issue. Unless you object, I'd like to close it.

**Comment by saikyun** [comment]
I have the same issue. Is there something I need to configure? Tried messing around with the settings for `company-mode`, but no success so far. I also tried the latest commit.

**Comment by Sodel-the-Vociferous** [comment]
I'll have another, closer look at this. Sorry for such a distraction! Hopefully I can figure out what on earth is going on.

**Comment by jefftrull** [comment]
I observe it as well (26.2, Melpa); would love to have a fix.

**Comment by Sodel-the-Vociferous** [comment]
I definitely believe you are all seeing this issue, but I just can't duplicate it myself.

Would any of you mind posting a copy of your .emacs configuration so I can test with it?

Also: which OS version are you using? CPU speed? (I'm starting to wonder if it's a race condition.)

**Comment by jefftrull** [comment]
```elisp
;; init file
(load-library "company")
(load-library "helm")
(load-library "helm-config")
(load-library "helm-company")

(add-hook 'c++-mode-hook
          (lambda ()
            (company-mode)
            (set (make-local-variable 'company-backends) '((company-etags)))
            (local-set-key (kbd "C-M-i") 'helm-company)
            ))
(setq company-idle-delay nil)
```
```c++
// test program
#include <iostream>
#include <string>
#include <chrono>

int bar(int i, int j)
{
  return i + j;
}

std::string baz(int k)
{
  return std::to_string(k);
}

int main()
{
  std::cout << "hello world\n";
  bar(1, 2);

  using namespace std::chrono;
  ba

}
```
Position point right after "ba", then hit `C-M-i` (helm shows "bar" and "baz"), then `C-g` - you now see company completion of the same thing.

**Comment by jefftrull** [comment]
Also you'll need to run `etags foo.cpp`.

Emacs 26.2, Ubuntu 19.04, i7-7700HQ CPU @ 2.80GHz

**Comment by Sodel-the-Vociferous** [comment]
Okay, *this* I can duplicate! It will take some time for me to get to the bottom of it, but now I have a test that works reliably on my end. Thank you so much!

**Comment by Sodel-the-Vociferous** [comment]
@jefftrull @tddsg  The fix I committed will fix invocations of `helm-company`, but not necessarily C-M-i. I don't think C-M-i runs `helm-company` but instead some other completion-at-point-function that also uses helm as its frontend interface.
